'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { CheckCircle, Copy, Printer, Home } from 'lucide-react'
import { useToast } from '@/lib/toast'

type SummaryItem = {
  name: string
  opening: number
  sold: number
  expected: number
  actual: number
  variance: number
}

type ShiftSummary = {
  shiftName: string
  shiftDate: string
  openedAt: string
  closedAt: string
  totalRevenue: number
  cashRevenue: number
  transferRevenue: number
  totalExpenses: number
  cashExpenses: number
  transferExpenses: number
  netRevenue: number
  orderCount: number
  stockItems: SummaryItem[]
}

export default function ShiftSummaryPage() {
  const router = useRouter()
  const toast  = useToast()
  const [summary, setSummary] = useState<ShiftSummary | null>(null)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    const saved = localStorage.getItem('shift_summary')
    if (saved) {
      setSummary(JSON.parse(saved))
    } else {
      router.push('/dashboard')
    }
  }, [router])

  const buildReportText = (s: ShiftSummary) => {
    // Calculate max item name length for consistent column width
    const maxNameLen = Math.min(
      Math.max(...s.stockItems.map(i => i.name.length), 4),
      14 // Cap at 14 characters to fit phone screen
    )
    
    const fitName = (name: string) => {
      if (name.length > maxNameLen) {
        return name.slice(0, maxNameLen - 1) + '…'
      }
      return name.padEnd(maxNameLen)
    }

    // Fixed column widths that fit on phone screen
    const COL_OPEN = 4
    const COL_SOLD = 4
    const COL_EXP = 4
    const COL_ACT = 4
    const COL_VAR = 5
    
    // Build table rows
    const tableRows = s.stockItems.map(i => {
      const varStr = i.variance > 0 ? `+${i.variance}` : `${i.variance}`
      return `│ ${fitName(i.name)} │ ${String(i.opening).padStart(COL_OPEN)} │ ${String(i.sold).padStart(COL_SOLD)} │ ${String(i.expected).padStart(COL_EXP)} │ ${String(i.actual).padStart(COL_ACT)} │ ${varStr.padStart(COL_VAR)} │`
    }).join('\n')

    // Build table borders
    const tableTop = `┌${'─'.repeat(maxNameLen + 2)}┬${'─'.repeat(COL_OPEN + 2)}┬${'─'.repeat(COL_SOLD + 2)}┬${'─'.repeat(COL_EXP + 2)}┬${'─'.repeat(COL_ACT + 2)}┬${'─'.repeat(COL_VAR + 2)}┐`
    const tableDivider = `├${'─'.repeat(maxNameLen + 2)}┼${'─'.repeat(COL_OPEN + 2)}┼${'─'.repeat(COL_SOLD + 2)}┼${'─'.repeat(COL_EXP + 2)}┼${'─'.repeat(COL_ACT + 2)}┼${'─'.repeat(COL_VAR + 2)}┤`
    const tableBottom = `└${'─'.repeat(maxNameLen + 2)}┴${'─'.repeat(COL_OPEN + 2)}┴${'─'.repeat(COL_SOLD + 2)}┴${'─'.repeat(COL_EXP + 2)}┴${'─'.repeat(COL_ACT + 2)}┴${'─'.repeat(COL_VAR + 2)}┘`
    
    const headerRow = `│ ${'Item'.padEnd(maxNameLen)} │ ${'Open'.padStart(COL_OPEN)} │ ${'Sold'.padStart(COL_SOLD)} │ ${'Exp'.padStart(COL_EXP)} │ ${'Act'.padStart(COL_ACT)} │ ${'Var'.padStart(COL_VAR)} │`

    const divider = '─'.repeat(32)

    const report = `UPTIMYZAS KITCHEN
═══════════════════════════════════════
SHIFT CLOSE REPORT
───────────────────────────────────────
Shift    : ${s.shiftName}
Date     : ${new Date(s.shiftDate).toLocaleDateString('en-NG', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
Opened   : ${new Date(s.openedAt).toLocaleTimeString('en-NG', { hour: '2-digit', minute: '2-digit' })}
Closed   : ${new Date(s.closedAt).toLocaleTimeString('en-NG', { hour: '2-digit', minute: '2-digit' })}
Orders   : ${s.orderCount || 0}
───────────────────────────────────────

REVENUE
  Cash       : ₦${(s.cashRevenue || 0).toLocaleString()}
  Transfer   : ₦${(s.transferRevenue || 0).toLocaleString()}
  Total      : ₦${s.totalRevenue.toLocaleString()}

EXPENSES
  Cash       : ₦${(s.cashExpenses || 0).toLocaleString()}
  Transfer   : ₦${(s.transferExpenses || 0).toLocaleString()}
  Total      : ₦${s.totalExpenses.toLocaleString()}

NET PROFIT : ₦${s.netRevenue.toLocaleString()}
───────────────────────────────────────

STOCK VARIANCE
${tableTop}
${headerRow}
${tableDivider}
${tableRows}
${tableBottom}
───────────────────────────────────────
Generated by Uptimyzas Kitchen`

    return '```' + report + '```'
  }

  const handleCopy = async () => {
    if (!summary) return
    try {
      await navigator.clipboard.writeText(buildReportText(summary))
      setCopied(true)
      toast('Report copied to clipboard!', 'success')
      setTimeout(() => setCopied(false), 3000)
    } catch {
      toast('Could not copy — try long-pressing the text', 'warning')
    }
  }

  const handlePrint = () => window.print()

  if (!summary) {
    return (
      <div className="min-h-screen bg-bg-subtle flex items-center justify-center">
        <div className="w-7 h-7 border-[3px] border-border border-t-primary rounded-full animate-spin" />
      </div>
    )
  }

  const isProfit = summary.netRevenue >= 0

  return (
    <div className="min-h-screen bg-bg-subtle">
      <div className="p-4 max-w-2xl mx-auto space-y-4 pb-10">

        {/* Success header */}
        <div className="bg-primary rounded-[18px] p-5 text-white text-center">
          <div className="w-14 h-14 rounded-full bg-white/20 flex items-center justify-center mx-auto mb-3">
            <CheckCircle size={28} className="text-white" />
          </div>
          <p className="t-h1 text-white">Shift Closed</p>
          <p className="t-body text-white/70 mt-1">{summary.shiftName} Shift</p>
          <p className="t-small text-white/50 mt-0.5">
            {new Date(summary.shiftDate).toLocaleDateString('en-NG', {
              weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
            })}
          </p>

          {/* Time range */}
          <div className="flex justify-center gap-6 mt-4 pt-4 border-t border-white/20">
            <div className="text-center">
              <p className="t-small text-white/50">Opened</p>
              <p className="t-mono text-white">
                {new Date(summary.openedAt).toLocaleTimeString('en-NG', {
                  hour: '2-digit', minute: '2-digit'
                })}
              </p>
            </div>
            <div className="text-center">
              <p className="t-small text-white/50">Closed</p>
              <p className="t-mono text-white">
                {new Date(summary.closedAt).toLocaleTimeString('en-NG', {
                  hour: '2-digit', minute: '2-digit'
                })}
              </p>
            </div>
            <div className="text-center">
              <p className="t-small text-white/50">Orders</p>
              <p className="t-mono text-white">{summary.orderCount || 0}</p>
            </div>
          </div>
        </div>

        {/* Net profit highlight */}
        <div className={`rounded-[18px] p-5 text-center ${
          isProfit ? 'bg-[#2E7D32]/10 border-2 border-[#2E7D32]/20' : 'bg-danger/10 border-2 border-danger/20'
        }`}>
          <p className="t-small text-text-muted uppercase tracking-widest mb-1">Net Profit</p>
          <p className={`text-[40px] font-semibold leading-none ${
            isProfit ? 'text-[#2E7D32]' : 'text-danger'
          }`}>
            ₦{summary.netRevenue.toLocaleString()}
          </p>
        </div>

        {/* Revenue */}
        <div className="card">
          <p className="t-h3 text-text-primary mb-3">Revenue</p>
          <div className="space-y-2">
            <div className="flex justify-between items-center">
              <p className="t-body text-text-secondary">Cash</p>
              <p className="t-mono text-[#2E7D32] font-medium">
                ₦{(summary.cashRevenue || 0).toLocaleString()}
              </p>
            </div>
            <div className="flex justify-between items-center">
              <p className="t-body text-text-secondary">Transfer</p>
              <p className="t-mono text-[#1565C0] font-medium">
                ₦{(summary.transferRevenue || 0).toLocaleString()}
              </p>
            </div>
            <div className="flex justify-between items-center pt-2 border-t border-border">
              <p className="t-h3 text-text-primary">Total</p>
              <p className="t-mono text-[#2E7D32] font-semibold">
                ₦{summary.totalRevenue.toLocaleString()}
              </p>
            </div>
          </div>
        </div>

        {/* Expenses */}
        <div className="card">
          <p className="t-h3 text-text-primary mb-3">Expenses</p>
          <div className="space-y-2">
            <div className="flex justify-between items-center">
              <p className="t-body text-text-secondary">Cash</p>
              <p className="t-mono text-danger font-medium">
                ₦{(summary.cashExpenses || 0).toLocaleString()}
              </p>
            </div>
            <div className="flex justify-between items-center">
              <p className="t-body text-text-secondary">Transfer</p>
              <p className="t-mono text-[#E65100] font-medium">
                ₦{(summary.transferExpenses || 0).toLocaleString()}
              </p>
            </div>
            <div className="flex justify-between items-center pt-2 border-t border-border">
              <p className="t-h3 text-text-primary">Total</p>
              <p className="t-mono text-danger font-semibold">
                ₦{summary.totalExpenses.toLocaleString()}
              </p>
            </div>
          </div>
        </div>

        {/* Stock variance table */}
        <div className="card">
          <p className="t-h3 text-text-primary mb-3">Stock Variance</p>
          <div className="overflow-x-auto -mx-1">
            <table className="w-full">
              <thead>
                <tr className="bg-bg-subtle">
                  {['Item', 'Open', 'Sold', 'Exp', 'Act', 'Var'].map((h, i) => (
                    <th
                      key={h}
                      className={`p-2 t-small text-text-muted font-medium ${
                        i === 0 ? 'text-left' : 'text-right'
                      }`}
                    >
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {summary.stockItems.map((item, idx) => (
                  <tr key={idx} className="border-b border-border">
                    <td className="p-2 t-body text-text-primary">{item.name}</td>
                    <td className="p-2 t-mono text-text-secondary text-right">{item.opening}</td>
                    <td className="p-2 t-mono text-text-secondary text-right">{item.sold}</td>
                    <td className="p-2 t-mono text-text-secondary text-right">{item.expected}</td>
                    <td className="p-2 t-mono text-text-secondary text-right">{item.actual}</td>
                    <td className={`p-2 t-mono text-right font-semibold ${
                      item.variance > 0
                        ? 'text-[#2E7D32]'
                        : item.variance < 0
                        ? 'text-danger'
                        : 'text-text-muted'
                    }`}>
                      {item.variance > 0 ? `+${item.variance}` : item.variance}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Preview of what will be copied */}
        <div className="bg-[#1a1a1a] rounded-xl p-4 overflow-x-auto">
          <p className="t-small text-text-muted mb-2">📋 Preview (what will be copied)</p>
          <pre className="text-xs text-[#e0e0e0] font-mono whitespace-pre-wrap break-words max-h-60 overflow-y-auto">
            {buildReportText(summary)}
          </pre>
        </div>

        {/* Action buttons */}
        <div className="grid grid-cols-2 gap-3">
          <button
            onClick={handleCopy}
            className="btn-secondary flex items-center justify-center gap-2"
          >
            <Copy size={16} />
            {copied ? 'Copied!' : 'Copy Report'}
          </button>
          <button
            onClick={handlePrint}
            className="btn-secondary flex items-center justify-center gap-2"
          >
            <Printer size={16} />
            Print
          </button>
        </div>

        <button
          onClick={() => router.push('/dashboard')}
          className="btn-primary w-full flex items-center justify-center gap-2"
        >
          <Home size={16} />
          Back to Dashboard
        </button>

        <p className="t-small text-text-muted text-center">
          Shift locked · No further orders can be taken
        </p>

      </div>
    </div>
  )
}